# Generated by Django 3.2.25 on 2026-07-02 18:21

from django.db import migrations, models


def migrate_old_occupations(apps, schema_editor):
    User = apps.get_model('users', 'User')
    # Old → New: Doctor('3')→Empleado('1'), Recepcion('2')→Cliente('2'), Paciente('1')→Empleado('1')
    mapping = {'3': '1', '2': '2', '1': '1'}
    for old, new in mapping.items():
        User.objects.filter(occupation=old).update(occupation=new)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_old_occupations),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Empleado'), ('2', 'Cliente')], max_length=3),
        ),
    ]
